language: java
sudo: false

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then 
    mvn clean deploy --settings target/travis/settings.xml; 
else 
    mvn clean verify --settings target/travis/settings.xml;
fi"

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - develop

env:
  global:
    - secure: "JwCmjYm7szOBRLEL24GvPumwQNokA6bcdpP1X5Zmj2QhGIFKlYeOHkgkiRQt+SSWH6ClcBSHWtCi9+OlvC4O1vOXoH4nuq2a3xeIP7t+oJDWqTM8J34zEzUX9lG1rHI87YbuTWWN8+6HsbUTbfHMLWxX+UgyYgaloqt5JiTyB7A="
    - secure: "sLJrG63Qgs9kXxGrVoLYuO5hV79t2RoEKoAFzMSTeCjG1JOxWWnuvlIzTnMQD3NU0IJy1YQrkuU8wWvjpk5+3Ue0/TZDDR2psqEomYyphnfRVUH/U593dbXxK6XREE7n/X/dvlaTXq2YLcKrO09SJUSwwlDt0LjkGLzYfHziN5s="

matrix:
  - LC_ALL=C
  - LC_ALL=pl_PL
  - LC_ALL_zh_CN
